#!/bin/bash

echo "=================================="
echo "Casino Poker - Deployment Setup"
echo "=================================="
echo ""
echo "Step 1: Firebase Setup"
echo "----------------------"
echo "1. Go to https://console.firebase.google.com/"
echo "2. Create a new project (or use existing)"
echo "3. Add a Web app to your project"
echo "4. Copy the Firebase config and update firebase-stats.js"
echo "5. Enable Firestore Database"
echo ""
echo "Step 2: Update Firebase Config"
echo "-------------------------------"
echo "Edit firebase-stats.js and replace:"
echo "  - apiKey"
echo "  - authDomain"
echo "  - projectId"
echo "  - storageBucket"
echo "  - messagingSenderId"
echo "  - appId"
echo ""
echo "Step 3: Deploy to Vercel"
echo "------------------------"
echo "Option A - CLI:"
echo "  npm install -g vercel"
echo "  vercel login"
echo "  vercel"
echo ""
echo "Option B - GitHub:"
echo "  1. Push code to GitHub"
echo "  2. Import to Vercel"
echo "  3. Deploy"
echo ""
echo "Option C - Drag & Drop:"
echo "  1. Go to vercel.com/new"
echo "  2. Drag entire folder"
echo "  3. Deploy"
echo ""
echo "Files ready for deployment:"
echo "  - index.html (main game)"
echo "  - firebase-stats.js (stats tracking)"
echo "  - package.json (dependencies)"
echo "  - vercel.json (config)"
echo "  - README.md (full docs)"
echo ""
echo "=================================="
